"use client";
import {useState} from "react";
import {LanternKo2D} from "@/components/mascot2d/LanternKo2D";
import type {ExpressionKey} from "@/components/mascot/LanternKoMeshV2";
import type {MascotAnim,MascotEmotions} from "@/lib/mascot/types";
const expressions:ExpressionKey[]=["neutral","happy","excited","surprised","sad","curious","confused","annoyed","focused","sleepy","proud","smug","mischievous","scared"];
const actions:MascotAnim[]=["idle","walk","run","jump","wave","think","sleep","point","stretch","nod","shy","celebrate","bow"];
const emotions:MascotEmotions={curiosity:.5,energy:.72,happiness:.45,boredom:.05,sleepiness:.08,attention:.8,confidence:.6,stress:.08};
const pill=(on:boolean)=>({whiteSpace:"nowrap" as const,padding:"9px 12px",borderRadius:999,border:"1px solid #d99b4666",background:on?"#d99b46":"#171113",color:on?"#160d0b":"#f7e9dd"});
export default function Mascot2DPreview(){const [expression,setExpression]=useState<ExpressionKey>("neutral");const [anim,setAnim]=useState<MascotAnim>("idle");const [x,setX]=useState(0);const [y,setY]=useState(0);const [depth,setDepth]=useState(1);return <main style={{minHeight:"100svh",background:"#0d0a0b",color:"#f7e9dd",padding:"20px",fontFamily:"system-ui"}}><h1 style={{fontSize:24,marginBottom:4}}>Lantern-ko 2.5D Lab</h1><p style={{opacity:.65,marginTop:0}}>Expression, action, gaze and depth review. Live mascot unchanged.</p><section style={{minHeight:360,display:"grid",placeItems:"center",border:"1px solid #d99b4644",borderRadius:24,background:"radial-gradient(circle at 50% 40%,#2b1916,#100c0d 68%)",overflow:"hidden"}}><LanternKo2D expression={expression} emotions={{...emotions,happiness:expression==="happy"?.9:.45,stress:expression==="scared"?.8:.08}} lookBias={{x,y}} anim={anim} depth={depth}/></section><p style={{fontSize:12,opacity:.55}}>EXPRESSION</p><div style={{display:"flex",gap:8,overflowX:"auto",paddingBottom:8}}>{expressions.map(e=><button key={e} onClick={()=>setExpression(e)} style={pill(e===expression)}>{e}</button>)}</div><p style={{fontSize:12,opacity:.55}}>ACTION</p><div style={{display:"flex",gap:8,overflowX:"auto",paddingBottom:16}}>{actions.map(a=><button key={a} onClick={()=>setAnim(a)} style={pill(a===anim)}>{a}</button>)}</div><label>Gaze X <input type="range" min="-1" max="1" step=".05" value={x} onChange={e=>setX(Number(e.target.value))} style={{width:"100%"}}/></label><label style={{display:"block",marginTop:12}}>Gaze Y <input type="range" min="-1" max="1" step=".05" value={y} onChange={e=>setY(Number(e.target.value))} style={{width:"100%"}}/></label><label style={{display:"block",marginTop:12}}>2.5D depth <input type="range" min="0" max="1" step=".05" value={depth} onChange={e=>setDepth(Number(e.target.value))} style={{width:"100%"}}/></label></main>}
