"use client";
import {useEffect,useRef,useState} from "react";
import type {CSSProperties} from "react";
import styles from "./face-rig-2d.module.css";
type Props={expression:string;blink:boolean;gazeX:number;gazeY:number;blush:number;turn?:number;mouthOpen?:number;mouthWide?:number;mouthMood?:number};
type Blend={happy:number;sad:number;surprised:number;sleepy:number;angry:number;thinking:number;smug:number};
const ZERO:Blend={happy:0,sad:0,surprised:0,sleepy:0,angry:0,thinking:0,smug:0};
const clamp=(v:number,lo=-1,hi=1)=>Math.min(hi,Math.max(lo,v));
const targetFor=(expression:string):Blend=>({happy:["happy","excited","proud","smug","mischievous"].includes(expression)?1:0,sad:expression==="sad"||expression==="scared"?1:0,surprised:expression==="surprised"||expression==="scared"?1:0,sleepy:expression==="sleepy"?1:0,angry:expression==="annoyed"||expression==="focused"?1:0,thinking:expression==="curious"||expression==="confused"?1:0,smug:expression==="smug"||expression==="mischievous"?1:0});
export function FaceRig2D({expression,blink,gazeX,gazeY,blush,turn=0,mouthOpen=0,mouthWide=0,mouthMood=0}:Props){
 const targetRef=useRef(targetFor(expression)),blendRef=useRef<Blend>({...ZERO,...targetRef.current}),[blend,setBlend]=useState<Blend>(blendRef.current);targetRef.current=targetFor(expression);
 useEffect(()=>{let raf=0,last=performance.now(),lastPaint=0,alive=true;const keys=(Object.keys(ZERO) as (keyof Blend)[]);const tick=(now:number)=>{if(!alive)return;const dt=Math.min(.05,(now-last)/1000);last=now;let moving=false;const next={...blendRef.current};for(const k of keys){const goal=targetRef.current[k],cur=next[k],rate=goal>cur?11.5:6.4,nextValue=cur+(goal-cur)*(1-Math.exp(-rate*dt));next[k]=Math.abs(goal-nextValue)<.002?goal:nextValue;if(Math.abs(goal-next[k])>.002)moving=true}blendRef.current=next;if(now-lastPaint>33&&(moving||now-lastPaint>180)){lastPaint=now;setBlend({...next})}raf=requestAnimationFrame(tick)};raf=requestAnimationFrame(tick);return()=>{alive=false;cancelAnimationFrame(raf)}},[]);
 const gx=clamp(gazeX/6),gy=clamp(gazeY/5),t=clamp(turn,-.6,.6),amount=Math.abs(t)/.6,squint=blend.angry*.16+blend.sleepy*.34+blend.smug*.12,openness=blink?0:clamp(1-squint+blend.surprised*.12,0,1.12),expressionOpen=Math.max(blend.surprised*.88,(expression==="excited"?blend.happy*.18:0),blend.thinking*.1),expressionWide=Math.max((expression==="excited"?blend.happy*.72:0),blend.happy*.42,blend.smug*.25,blend.thinking*.12),expressionMood=blend.happy*.72+blend.smug*.18-blend.sad*.7-blend.angry*.28-blend.sleepy*.12,proceduralOpen=clamp(Math.max(expressionOpen,mouthOpen),0,1),proceduralWide=clamp(Math.max(expressionWide,mouthWide),0,1),mood=clamp(expressionMood+mouthMood),browL=-blend.sad*17+blend.angry*18-blend.thinking*8,browR=blend.sad*17-blend.angry*18+blend.smug*7,browLift=blend.thinking*5+blend.smug*1.5;
 const vars={"--fx":`${gazeX}px`,"--fy":`${gazeY}px`,"--fb":blush,"--eye-open":openness,"--pupil-x":`${gx*1.4}px`,"--pupil-y":`${gy*.9}px`,"--iris-scale":1-blend.surprised*.06+blend.angry*.04,"--lid-bias":`${gy*1.5}px`,"--turn":t,"--turn-amount":amount,"--feature-shift":`${t*5.2}px`,"--nose-turn":`${t*7.2}px`,"--mouth-turn":`${t*4.6}px`,"--mouth-open":proceduralOpen,"--mouth-wide":proceduralWide,"--mouth-mood":mood,"--mouth-asym":`${t*2.2}px`,"--brow-left":`${browL}deg`,"--brow-right":`${browR}deg`,"--brow-left-y":`${-blend.thinking*5}px`,"--brow-right-y":`${-blend.smug*3}px`,"--mouth-curve":mood,"--sadness":blend.sad,"--thinking":blend.thinking,"--smug":blend.smug} as CSSProperties;
 return <div className={styles.rig} style={vars} data-expression={expression} data-turn={t<-.08?"left":t>.08?"right":"front"}>
  <div className={styles.nose}/><div className={`${styles.blush} ${styles.blushL}`}/><div className={`${styles.blush} ${styles.blushR}`}/>
  {([-1,1] as const).map(side=>{const near=t===0?false:(t>0?side>0:side<0);return <div key={side} data-depth={near?"near":"far"} className={`${styles.eye} ${side<0?styles.left:styles.right}`}><div className={styles.eyeWhite}/><div className={styles.gaze}><div className={styles.iris}><i/><b/><span/></div></div><div className={styles.upperLid}/><div className={styles.lash}/><div className={styles.lowerLash}/></div>})}
  <div className={`${styles.brow} ${styles.browL}`}/><div className={`${styles.brow} ${styles.browR}`}/>
  <div className={`${styles.mouth} ${proceduralOpen>.08?styles.proceduralOpen:styles.morphedMouth}`}>{proceduralOpen>.08&&<i/>}</div>
 </div>;
}
