"use client";
import {useCallback,useEffect,useRef,useState} from "react";
import {useMascotStore} from "@/lib/mascot/store";
import {worldToScreen,screenToWorld} from "@/lib/mascot/world-coords";
import {buildTerrain,getHomePlatform,nearestPlatform,planHops,type TerrainPlatform} from "@/lib/mascot/page-terrain";
import {clearMovementCommand,peekMovementCommand} from "@/lib/mascot/movement-command";
import {areInteractionsEnabled} from "@/lib/mascot/a11y";
import {wireStoreMovement} from "@/lib/mascot/wire-movement";
import {installBuiltinMascotEvents} from "@/lib/mascot/builtin-events";
import {installNexusAttentionBridge} from "@/lib/mascot/nexus-attention-bridge";
import {Mascot2DEngineAdapter} from "./Mascot2DEngineAdapter";
import type {PerchPose} from "./types";
type Point={x:number;y:number};type Phase="idle"|"anticipate"|"travel";type Interaction="none"|"hover"|"grab"|"poke";type PosePhase="stable"|"balance"|"settle";
const HOME:Point={x:1.05,y:-.72},clamp=(n:number,a:number,b:number)=>Math.max(a,Math.min(b,n));
const perch=(p:TerrainPlatform,fromX=p.x):Point=>{const top=p.y+p.hh;if(p.type==="card"||p.type==="search"||p.type==="modal"||p.type==="drawer"||p.type==="dropdown"){const side=fromX<=p.x?-1:1,edge=Math.min(Math.max(p.hw*.68,.055),p.type==="card"?.22:.32);return{x:p.x+side*edge,y:top}}return{x:p.x,y:top}};
const choosePerchPose=(p:TerrainPlatform,at:Point):PerchPose=>{const wide=p.hw>.18,tall=p.hh>.28,side=at.x<=p.x?"left":"right";if((p.type==="modal"||p.type==="drawer"||p.type==="dropdown")&&tall)return side==="left"?"peek-left":"peek-right";if(p.type==="card"&&wide)return"sit";if((p.type==="card"||p.type==="search")&&p.hh>.13)return"crouch";return"stand"};
export function LiveMascot2D({reducedMotion=false}:{reducedMotion?:boolean}){
 const storePos=useMascotStore(s=>s.position),setPosition=useMascotStore(s=>s.setPosition),setTarget=useMascotStore(s=>s.setTarget),setAnim=useMascotStore(s=>s.setAnim);
 const [world,setWorld]=useState<Point>(()=>storePos??HOME),[dragging,setDragging]=useState(false),[landed,setLanded]=useState(false),[yaw,setYaw]=useState(0),[moveSpeed,setMoveSpeed]=useState(0),[lift,setLift]=useState(0),[phase,setPhase]=useState<Phase>("idle"),[interaction,setInteraction]=useState<Interaction>("none"),[gaze,setGaze]=useState<Point>({x:0,y:0}),[perchPose,setPerchPose]=useState<PerchPose>("stand"),[posePhase,setPosePhase]=useState<PosePhase>("stable");
 const platforms=useRef<TerrainPlatform[]>([]),route=useRef<TerrainPlatform[]>([]),active=useRef<string|null>(null),raf=useRef<number|null>(null),worldRef=useRef(world),landTimer=useRef<number|null>(null),interactionTimer=useRef<number|null>(null),poseTimers=useRef<number[]>([]),lastFrame=useRef(0),lastYaw=useRef(0),phaseRef=useRef<Phase>("idle"),anticipateUntil=useRef(0),legStart=useRef<Point|null>(null),legDest=useRef<Point|null>(null),downAt=useRef({x:0,y:0,t:0}),lastPoke=useRef(0);worldRef.current=world;phaseRef.current=phase;const setMotionPhase=(p:Phase)=>{phaseRef.current=p;setPhase(p)};
 const clearPoseTimers=useCallback(()=>{poseTimers.current.forEach(clearTimeout);poseTimers.current=[]},[]);
 const stagePerch=useCallback((next:PerchPose)=>{clearPoseTimers();if(reducedMotion||next==="stand"){setPerchPose(next);setPosePhase("stable");return}setPerchPose("stand");setPosePhase("balance");poseTimers.current.push(window.setTimeout(()=>{setPerchPose(next);setPosePhase("settle")},170));poseTimers.current.push(window.setTimeout(()=>setPosePhase("stable"),next==="sit"?620:500))},[clearPoseTimers,reducedMotion]);
 const react=useCallback((kind:Interaction,anim:"surprised"|"happy"|"shy"|"idle",ms=650)=>{setInteraction(kind);setAnim(anim);if(interactionTimer.current)clearTimeout(interactionTimer.current);interactionTimer.current=window.setTimeout(()=>{setInteraction("none");setGaze({x:0,y:0});if(!peekMovementCommand())setAnim("idle")},ms)},[setAnim]);
 useEffect(()=>{wireStoreMovement();installBuiltinMascotEvents();installNexusAttentionBridge();let scrollTimer=0;const rebuild=()=>{try{platforms.current=buildTerrain()}catch(e){console.warn("[Lantern-ko 2D] terrain rebuild failed",e)}},onScroll=()=>{clearTimeout(scrollTimer);scrollTimer=window.setTimeout(rebuild,90)};rebuild();const a=window.setTimeout(rebuild,250),b=window.setTimeout(rebuild,900);window.addEventListener("resize",rebuild);window.addEventListener("scroll",onScroll,{passive:true});return()=>{clearTimeout(a);clearTimeout(b);clearTimeout(scrollTimer);if(interactionTimer.current)clearTimeout(interactionTimer.current);clearPoseTimers();window.removeEventListener("resize",rebuild);window.removeEventListener("scroll",onScroll)}},[clearPoseTimers]);
 useEffect(()=>{let alive=true;lastFrame.current=performance.now();const pulse=(now:number)=>{if(!alive)return;const dt=Math.min(.05,Math.max(.001,(now-lastFrame.current)/1000));lastFrame.current=now;if(!dragging){const cmd=peekMovementCommand();if(cmd&&cmd.id!==active.current){stagePerch("stand");active.current=cmd.id;const ps=platforms.current,dest=(cmd.platformId&&ps.find(p=>p.id===cmd.platformId))||nearestPlatform(ps,cmd.target.x,cmd.target.y),from=nearestPlatform(ps,worldRef.current.x,worldRef.current.y);route.current=dest?planHops(from,dest,ps):[];if(!route.current.length&&dest)route.current=[dest];if(!route.current.length)route.current=[{id:"direct",type:"generic",x:cmd.target.x,y:cmd.target.y,hw:.05,hh:0,priority:1,clientX:0,clientY:0}];legStart.current={...worldRef.current};const first=route.current[0];if(first){legDest.current=perch(first,worldRef.current.x);const dx=legDest.current.x-worldRef.current.x,dy=legDest.current.y-worldRef.current.y;setGaze({x:clamp(dx*1.8,-1,1),y:clamp(-dy*1.5,-1,1)})}if(!reducedMotion){setMotionPhase("anticipate");anticipateUntil.current=now+115}else setMotionPhase("travel")}
 if(phaseRef.current==="anticipate"){setLift(-4);setMoveSpeed(0);if(now>=anticipateUntil.current){setLift(0);setMotionPhase("travel")}}else{const goal=route.current[0];if(goal){const dest=legDest.current??perch(goal,worldRef.current.x),cur=worldRef.current,dx=dest.x-cur.x,dy=dest.y-cur.y,d=Math.hypot(dx,dy);if(d<.025){route.current.shift();worldRef.current=dest;setWorld(dest);setPosition(dest);setLift(0);setMoveSpeed(0);setLanded(true);if(landTimer.current)clearTimeout(landTimer.current);landTimer.current=window.setTimeout(()=>setLanded(false),300);if(route.current.length){stagePerch("stand");legStart.current={...dest};const n=route.current[0];legDest.current=perch(n,dest.x);setGaze({x:clamp((legDest.current.x-dest.x)*1.8,-1,1),y:clamp((dest.y-legDest.current.y)*1.5,-1,1)});setMotionPhase("travel")}else if(cmd){stagePerch(choosePerchPose(goal,dest));if(goal.type==="card"||goal.type==="search"||goal.type==="modal"||goal.type==="drawer"||goal.type==="dropdown"){const toward=clamp((goal.x-dest.x)*3,-.6,.6);lastYaw.current=toward;setYaw(toward);setGaze({x:clamp((goal.x-dest.x)*4,-1,1),y:.7})}else setGaze({x:0,y:0});legDest.current=null;clearMovementCommand(cmd.id);active.current=null;setTarget(null);setMotionPhase("idle");setAnim("idle")}}else{const raw=(cmd?.speed??1)*(reducedMotion?1.8:1.05),step=Math.min(d,raw*dt),next={x:cur.x+dx/d*step,y:cur.y+dy/d*step},desired=clamp(dx*2.4,-.6,.6),smooth=lastYaw.current+(desired-lastYaw.current)*Math.min(1,dt*8);lastYaw.current=smooth;setYaw(smooth);setMoveSpeed(clamp(raw/1.8,0,1));if(!reducedMotion&&legStart.current){const total=Math.max(.001,Math.hypot(dest.x-legStart.current.x,dest.y-legStart.current.y)),progress=1-Math.min(1,d/total);setLift(Math.sin(progress*Math.PI)*Math.min(28,10+total*12))}else setLift(0);worldRef.current=next;setWorld(next);setPosition(next);setAnim(cmd?.mode==="run"||d>.5?"run":"walk")}}else{setLift(0);setMoveSpeed(0)}}}raf.current=requestAnimationFrame(pulse)};raf.current=requestAnimationFrame(pulse);return()=>{alive=false;if(raf.current)cancelAnimationFrame(raf.current);if(landTimer.current)clearTimeout(landTimer.current)}},[dragging,reducedMotion,setPosition,setTarget,setAnim,stagePerch]);
 const screen=worldToScreen(world.x,world.y),visualTop=-276-lift,trackPointer=useCallback((x:number,y:number)=>{const cx=screen.clientX,cy=screen.clientY-170;setGaze({x:clamp((x-cx)/120,-1,1),y:clamp((y-cy)/100,-1,1)})},[screen.clientX,screen.clientY]);
 const down=useCallback((e:React.PointerEvent)=>{if(!areInteractionsEnabled())return;e.preventDefault();downAt.current={x:e.clientX,y:e.clientY,t:performance.now()};trackPointer(e.clientX,e.clientY);e.currentTarget.setPointerCapture?.(e.pointerId);clearMovementCommand();route.current=[];legDest.current=null;active.current=null;stagePerch("stand");setDragging(true);setInteraction("grab");setLift(0);setMotionPhase("idle");setMoveSpeed(0);setAnim("surprised")},[setAnim,trackPointer,stagePerch]);
 const move=useCallback((e:React.PointerEvent)=>{trackPointer(e.clientX,e.clientY);if(!dragging)return;e.preventDefault();const p=screenToWorld(e.clientX,e.clientY),aspect=window.innerWidth/Math.max(window.innerHeight,1),next={x:clamp(p.x,-aspect+.12,aspect-.12),y:clamp(p.y,-.9,.9)};worldRef.current=next;setWorld(next);setPosition(next)},[dragging,setPosition,trackPointer]);
 const up=useCallback((e:React.PointerEvent)=>{if(!dragging)return;e.preventDefault();const travel=Math.hypot(e.clientX-downAt.current.x,e.clientY-downAt.current.y),held=performance.now()-downAt.current.t;setDragging(false);const nearest=nearestPlatform(platforms.current,worldRef.current.x,worldRef.current.y);if(nearest){const snap=perch(nearest,worldRef.current.x);worldRef.current=snap;setWorld(snap);setPosition(snap);stagePerch(choosePerchPose(nearest,snap));if(nearest.type==="card"||nearest.type==="search"||nearest.type==="modal"||nearest.type==="drawer"||nearest.type==="dropdown"){const toward=clamp((nearest.x-snap.x)*3,-.6,.6);lastYaw.current=toward;setYaw(toward);setGaze({x:clamp((nearest.x-snap.x)*4,-1,1),y:.7})}}setLanded(true);if(landTimer.current)clearTimeout(landTimer.current);landTimer.current=window.setTimeout(()=>setLanded(false),380);if(travel<10&&held<350){const now=performance.now(),rapid=now-lastPoke.current<900;lastPoke.current=now;react("poke",rapid?"shy":"happy",rapid?850:600)}else react("none","shy",650)},[dragging,setPosition,react,stagePerch]);
 const enter=useCallback((e:React.PointerEvent)=>{if(!dragging&&interaction==="none"){setInteraction("hover");trackPointer(e.clientX,e.clientY);setYaw(y=>y*.35)}},[dragging,interaction,trackPointer]),leave=useCallback(()=>{if(!dragging&&interaction==="hover"){setInteraction("none");setGaze({x:0,y:0})}},[dragging,interaction]);const home=getHomePlatform(platforms.current);
 return <><div className="mascot-home-pad" aria-hidden data-renderer="2d" style={home?{left:home.clientX,top:home.clientY}:undefined}/><div style={{position:"fixed",left:screen.clientX,top:screen.clientY,width:1,height:1,zIndex:70,pointerEvents:"none",transform:"translate3d(0,0,0)"}} data-mascot-renderer="2d"><div data-motion-phase={phase} data-pose-phase={posePhase} data-interaction={interaction} style={{position:"absolute",left:-110,top:visualTop,pointerEvents:"auto",touchAction:"none",cursor:dragging?"grabbing":"grab",transition:phase==="anticipate"?"top 100ms ease-out":"none"}} onPointerEnter={enter} onPointerLeave={leave} onPointerDown={down} onPointerMove={move} onPointerUp={up} onPointerCancel={up}><Mascot2DEngineAdapter depth={reducedMotion?.45:1} yaw={yaw} speed={moveSpeed} gazeOverride={gaze} justLanded={landed} perchPose={perchPose}/></div></div></>;
}
