"use client";

import * as THREE from "three";
import { forwardRef, useMemo, useRef } from "react";
import { useFrame } from "@react-three/fiber";
import type { MascotAnim, MascotEmotions } from "@/lib/mascot/types";
import { resolveFaceRigPose } from "@/lib/mascot/rig-adapter";

export type ExpressionKey = "neutral" | "happy" | "excited" | "curious" | "confused" | "surprised" | "embarrassed" | "sad" | "sleepy" | "scared" | "annoyed" | "proud" | "mischievous" | "focused" | "smug";
export type MouthVariant = "smile" | "bigSmile" | "frown" | "openO" | "flat" | "wobble";
export type MeshExpressionPose = { brow:[number,number]; browY:number; eyeY:number; mouth:MouthVariant; cheek:number; pulse:number };

export const EXPRESSIONS:Record<ExpressionKey,MeshExpressionPose>={
 neutral:{brow:[0.05,-0.05],browY:0,eyeY:1,mouth:"flat",cheek:0.15,pulse:0.4}, happy:{brow:[0.15,-0.15],browY:0.01,eyeY:0.85,mouth:"smile",cheek:0.4,pulse:0.6}, excited:{brow:[0.3,-0.3],browY:0.03,eyeY:1.15,mouth:"bigSmile",cheek:0.5,pulse:1.5}, curious:{brow:[0.3,-0.05],browY:0.02,eyeY:1,mouth:"openO",cheek:0.2,pulse:0.7}, confused:{brow:[0.25,-0.2],browY:0.01,eyeY:0.85,mouth:"wobble",cheek:0.1,pulse:0.45}, surprised:{brow:[-0.35,0.35],browY:0.04,eyeY:1.35,mouth:"openO",cheek:0.15,pulse:1.3}, embarrassed:{brow:[0.08,-0.08],browY:-0.01,eyeY:0.7,mouth:"flat",cheek:0.85,pulse:0.55}, sad:{brow:[-0.28,0.28],browY:-0.015,eyeY:0.65,mouth:"frown",cheek:0.05,pulse:0.25}, sleepy:{brow:[0.08,-0.08],browY:-0.02,eyeY:0.12,mouth:"flat",cheek:0.08,pulse:0.15}, scared:{brow:[-0.35,0.35],browY:0.03,eyeY:1.25,mouth:"openO",cheek:0.08,pulse:1.4}, annoyed:{brow:[-0.22,0.22],browY:-0.01,eyeY:0.75,mouth:"frown",cheek:0.12,pulse:0.35}, proud:{brow:[0.12,-0.12],browY:0.015,eyeY:0.95,mouth:"smile",cheek:0.35,pulse:0.7}, mischievous:{brow:[0.28,-0.08],browY:0.02,eyeY:0.8,mouth:"smile",cheek:0.28,pulse:0.9}, focused:{brow:[-0.1,0.1],browY:0.01,eyeY:0.9,mouth:"flat",cheek:0.1,pulse:0.5}, smug:{brow:[0.22,-0.05],browY:0.01,eyeY:0.7,mouth:"smile",cheek:0.3,pulse:0.65}
};
export type LegacyPose=MeshExpressionPose&{browRotZ:[number,number];eyeScaleY:number;tipPulseHz:number;cheekOpacity:number;headTilt:number};
export function toLegacyPose(p:MeshExpressionPose):LegacyPose{return{...p,browRotZ:p.brow,eyeScaleY:p.eyeY,tipPulseHz:p.pulse,cheekOpacity:p.cheek,headTilt:0};}

const HEAD_R=0.42,BODY_R=HEAD_R*0.52,BODY_LEN=HEAD_R*0.55,ARM_R=HEAD_R*0.17,ARM_LEN=HEAD_R*0.55,TIP_R=HEAD_R*0.16,STEM_LEN=HEAD_R*0.38,FACE=1.14;
const PALETTE={skin:"#f0a898",blush:"#f47f78",eye:"#241711",eyeWhite:"#fff8f1",iris:"#d98a32",irisLight:"#ffc85d",irisDeep:"#7d431f",eyeHighlight:"#fffdf8",mouth:"#c4786a",tip:"#ffd9a8",brow:"#2a1810",pupil:"#3b2118"};
const DEFAULT_EMOTIONS:MascotEmotions={curiosity:0.5,energy:0.5,happiness:0.5,boredom:0.2,sleepiness:0.1,attention:0.5,confidence:0.5,stress:0.1};
export type LanternKoMeshProps={expression?:ExpressionKey;emotions?:MascotEmotions;lookBias?:{x:number;y:number};anim?:MascotAnim;yaw?:number;speed?:number;justLanded?:boolean};
const damp=(c:number,t:number,l:number,dt:number)=>THREE.MathUtils.damp(c,t,l,dt);

function mouthWeights(curve:number,open:number,expression:ExpressionKey):Record<MouthVariant,number>{const w:Record<MouthVariant,number>={smile:0,bigSmile:0,frown:0,openO:0,flat:0,wobble:0};if(open>0.35){w.openO=Math.min(1,(open-0.2)/0.55);if(curve>0.15)w.smile=Math.max(0,1-w.openO)*Math.min(1,curve);else if(curve<-0.15)w.frown=Math.max(0,1-w.openO)*Math.min(1,-curve);else w.flat=Math.max(0,1-w.openO)*0.4;}else if(curve>0.55){w.bigSmile=Math.min(1,(curve-0.35)/0.45);w.smile=Math.max(0,1-w.bigSmile);}else if(curve>0.12){w.smile=Math.min(1,(curve-0.05)/0.4);w.flat=Math.max(0,1-w.smile)*0.35;}else if(curve<-0.25){w.frown=Math.min(1,(-curve-0.1)/0.5);w.flat=Math.max(0,1-w.frown)*0.3;}else if(expression==="confused"){w.wobble=0.75;w.flat=0.25;}else w.flat=1;const sum=Object.values(w).reduce((a,b)=>a+b,0)||1;for(const k of Object.keys(w) as MouthVariant[])w[k]/=sum;return w;}
const MOUTH_ASPECT:Record<MouthVariant,number>={smile:0.58,bigSmile:0.62,frown:0.72,openO:1,flat:1,wobble:0.78};

function makeBlushTexture(){const size=64,data=new Uint8Array(size*size*4);for(let y=0;y<size;y++)for(let x=0;x<size;x++){const nx=(x/(size-1))*2-1,ny=(y/(size-1))*2-1,d=Math.sqrt(nx*nx+ny*ny),a=Math.max(0,1-d);const i=(y*size+x)*4;data[i]=244;data[i+1]=112;data[i+2]=108;data[i+3]=Math.round(Math.pow(a,2.15)*255);}const tex=new THREE.DataTexture(data,size,size,THREE.RGBAFormat);tex.magFilter=THREE.LinearFilter;tex.minFilter=THREE.LinearFilter;tex.needsUpdate=true;return tex;}

export const LanternKoMesh=forwardRef<THREE.Group,LanternKoMeshProps>(function LanternKoMesh({expression="neutral",emotions=DEFAULT_EMOTIONS,lookBias={x:0,y:0},anim="idle",yaw=0,speed=0,justLanded=false},ref){
 const root=useRef<THREE.Group>(null),bodyGroup=useRef<THREE.Group>(null),armL=useRef<THREE.Group>(null),armR=useRef<THREE.Group>(null),head=useRef<THREE.Group>(null),tipGroup=useRef<THREE.Group>(null);
 const tip=useRef<THREE.Mesh>(null),glow=useRef<THREE.Mesh>(null),irisL=useRef<THREE.Group>(null),irisR=useRef<THREE.Group>(null),lidL=useRef<THREE.Mesh>(null),lidR=useRef<THREE.Mesh>(null),browL=useRef<THREE.Mesh>(null),browR=useRef<THREE.Mesh>(null),cheekL=useRef<THREE.Mesh>(null),cheekR=useRef<THREE.Mesh>(null);
 const mouthRefs=useRef<Record<MouthVariant,THREE.Mesh|null>>({smile:null,bigSmile:null,frown:null,openO:null,flat:null,wobble:null});
 const squashEnv=useRef(0),blinkTimer=useRef(2.2),blinkAmount=useRef(0),headAim=useRef(new THREE.Vector2()),settlePhase=useRef(0),tipLag=useRef(new THREE.Vector2());const browBaseY=HEAD_R*0.25;
 const materials=useMemo(()=>{const skin=new THREE.MeshStandardMaterial({color:PALETTE.skin,roughness:0.45,metalness:0.05}),eye=new THREE.MeshStandardMaterial({color:PALETTE.eye,roughness:0.32}),eyeWhite=new THREE.MeshStandardMaterial({color:PALETTE.eyeWhite,roughness:0.34}),iris=new THREE.MeshStandardMaterial({color:PALETTE.iris,roughness:0.28,emissive:PALETTE.irisDeep,emissiveIntensity:0.08}),irisLight=new THREE.MeshBasicMaterial({color:PALETTE.irisLight}),pupil=new THREE.MeshStandardMaterial({color:PALETTE.pupil,roughness:0.3}),mouth=new THREE.MeshStandardMaterial({color:PALETTE.mouth,roughness:0.4}),brow=new THREE.MeshStandardMaterial({color:PALETTE.brow,roughness:0.6}),tipMat=new THREE.MeshStandardMaterial({color:PALETTE.tip,emissive:PALETTE.tip,emissiveIntensity:0.6,roughness:0.3}),glowMat=new THREE.MeshBasicMaterial({color:PALETTE.tip,transparent:true,opacity:0.22,blending:THREE.AdditiveBlending,depthWrite:false}),hl=new THREE.MeshBasicMaterial({color:PALETTE.eyeHighlight}),lid=new THREE.MeshStandardMaterial({color:PALETTE.skin,roughness:0.45});const blushTex=makeBlushTexture(),blushL=new THREE.MeshBasicMaterial({map:blushTex,transparent:true,opacity:0.36,depthWrite:false,side:THREE.DoubleSide}),blushR=blushL.clone();return{skin,eye,eyeWhite,iris,irisLight,pupil,mouth,brow,tipMat,glowMat,hl,lid,blushL,blushR};},[]);
 useFrame((state,delta)=>{const dt=Math.min(delta,0.05),t=state.clock.elapsedTime;blinkTimer.current-=dt;if(blinkTimer.current<=0){blinkAmount.current=1;blinkTimer.current=2.5+Math.random()*3;}blinkAmount.current=Math.max(0,blinkAmount.current-dt*7);const r=resolveFaceRigPose(expression,emotions,anim,t,lookBias,blinkAmount.current);const gx=r.pupilX*HEAD_R*0.045,gy=r.pupilY*HEAD_R*0.034;const bases=[[-HEAD_R*0.30,irisL],[HEAD_R*0.30,irisR]] as const;for(const [bx,eyeRig] of bases){if(eyeRig.current){eyeRig.current.position.x=damp(eyeRig.current.position.x,bx+gx,18,dt);eyeRig.current.position.y=damp(eyeRig.current.position.y,HEAD_R*0.005+gy,18,dt);}}
 if(lidL.current&&lidR.current){const cl=1-THREE.MathUtils.clamp(r.eyeOpenL,0,1),cr=1-THREE.MathUtils.clamp(r.eyeOpenR,0,1),ll=cl>0.82?11:16,lr=cr>0.82?11:16;lidL.current.scale.y=damp(lidL.current.scale.y,0.045+cl*1.35,ll,dt);lidR.current.scale.y=damp(lidR.current.scale.y,0.045+cr*1.35,lr,dt);lidL.current.position.y=damp(lidL.current.position.y,HEAD_R*(0.17-cl*0.14),ll,dt);lidR.current.position.y=damp(lidR.current.position.y,HEAD_R*(0.17-cr*0.14),lr,dt);}
 if(head.current){const lm=Math.hypot(lookBias.x,lookBias.y),hl=3.8+Math.min(5.5,lm*7);headAim.current.x=damp(headAim.current.x,r.headYaw,hl,dt);headAim.current.y=damp(headAim.current.y,r.headPitch,hl,dt);head.current.rotation.y=headAim.current.x;head.current.rotation.x=headAim.current.y;head.current.rotation.z=damp(head.current.rotation.z,r.headRoll,6,dt);}if(browL.current&&browR.current){browL.current.rotation.z=damp(browL.current.rotation.z,r.browL,8,dt);browR.current.rotation.z=damp(browR.current.rotation.z,r.browR,8,dt);}
 const weights=mouthWeights(r.mouthCurve,r.mouthOpen,expression),wide=0.85+r.mouthWide*0.35;(Object.keys(mouthRefs.current) as MouthVariant[]).forEach(k=>{const m=mouthRefs.current[k];if(!m)return;const target=weights[k]*wide,s=Math.max(damp(m.scale.x||0.0001,Math.max(target,0.0001),12,dt),0.0001);m.scale.set(s,s*MOUTH_ASPECT[k],s);m.visible=s>0.015;});if(cheekL.current&&cheekR.current){const v=0.28+Math.pow(r.blush,0.85)*0.62;(cheekL.current.material as THREE.MeshBasicMaterial).opacity=damp((cheekL.current.material as THREE.MeshBasicMaterial).opacity,v,6,dt);(cheekR.current.material as THREE.MeshBasicMaterial).opacity=damp((cheekR.current.material as THREE.MeshBasicMaterial).opacity,v,6,dt);}
 if(tip.current){const mat=tip.current.material as THREE.MeshStandardMaterial,hz=0.55+emotions.energy*0.8+(EXPRESSIONS[expression]?.pulse??0.4)*0.15,p=0.55+Math.sin(t*hz*Math.PI*2)*0.4;mat.emissiveIntensity=p;if(glow.current)(glow.current.material as THREE.MeshBasicMaterial).opacity=0.12+p*0.14;}if(tipGroup.current){tipLag.current.x=damp(tipLag.current.x,Math.sin(t*2.2)*0.05*(0.4+speed),5,dt);tipLag.current.y=damp(tipLag.current.y,-yaw*0.15,4,dt);tipGroup.current.rotation.x=tipLag.current.x;tipGroup.current.rotation.z=tipLag.current.y;}if(justLanded)squashEnv.current=1;squashEnv.current=damp(squashEnv.current,0,6,dt);const sq=squashEnv.current;if(bodyGroup.current)bodyGroup.current.scale.set(1+sq*0.12,1-sq*0.18,1+sq*0.12);settlePhase.current+=dt*9;const wob=Math.sin(settlePhase.current)*sq*0.25;if(armL.current)armL.current.rotation.x=wob;if(armR.current)armR.current.rotation.x=-wob;if(root.current)root.current.position.y=Math.sin(t*1.4)*0.015*(0.5+speed);});
 const setRoot=(n:THREE.Group|null)=>{root.current=n;if(typeof ref==="function")ref(n);else if(ref)ref.current=n;};
 const eyeSize=HEAD_R*0.175*FACE,irisSize=HEAD_R*0.112*FACE,pupilSize=HEAD_R*0.047*FACE,lidSize=HEAD_R*0.19*FACE,browW=HEAD_R*0.25*FACE,browH=HEAD_R*0.028*FACE;
 return <group ref={setRoot}><group ref={bodyGroup} name="Body" position={[0,-HEAD_R*0.7,0]}><mesh castShadow><capsuleGeometry args={[BODY_R,BODY_LEN,10,12]}/><primitive object={materials.skin} attach="material"/></mesh><group ref={armL} name="ArmL" position={[-BODY_R-ARM_R*0.55,BODY_LEN*0.15,0]} rotation={[0,0,0.35]}><mesh><capsuleGeometry args={[ARM_R,ARM_LEN,6,8]}/><primitive object={materials.skin} attach="material"/></mesh></group><group ref={armR} name="ArmR" position={[BODY_R+ARM_R*0.55,BODY_LEN*0.15,0]} rotation={[0,0,-0.35]}><mesh><capsuleGeometry args={[ARM_R,ARM_LEN,6,8]}/><primitive object={materials.skin} attach="material"/></mesh></group></group>
 <group ref={head} name="Head" position={[0,HEAD_R*0.55,0]}><mesh castShadow><sphereGeometry args={[HEAD_R,28,24]}/><primitive object={materials.skin} attach="material"/></mesh>
 <mesh ref={cheekL} position={[-HEAD_R*0.43,-HEAD_R*0.16,HEAD_R*0.995]} scale={[HEAD_R*0.40,HEAD_R*0.22,1]}><planeGeometry args={[1,1]}/><primitive object={materials.blushL} attach="material"/></mesh><mesh ref={cheekR} position={[HEAD_R*0.43,-HEAD_R*0.16,HEAD_R*0.995]} scale={[HEAD_R*0.40,HEAD_R*0.22,1]}><planeGeometry args={[1,1]}/><primitive object={materials.blushR} attach="material"/></mesh>
 {([-1,1] as const).map(side=>(<group key={side}>
  <mesh name={side<0?"EyeL":"EyeR"} position={[side*HEAD_R*0.30,HEAD_R*0.005,HEAD_R*0.915]} scale={[0.94,1.20,0.58]}><sphereGeometry args={[eyeSize,24,20]}/><primitive object={materials.eye} attach="material"/></mesh>
  <mesh position={[side*HEAD_R*0.30,HEAD_R*0.002,HEAD_R*0.965]} scale={[0.78,1.02,0.48]}><sphereGeometry args={[eyeSize,24,20]}/><primitive object={materials.eyeWhite} attach="material"/></mesh>
  <group ref={side<0?irisL:irisR} position={[side*HEAD_R*0.30,HEAD_R*0.005,0]}>
   <mesh position={[0,0,HEAD_R*1.035]} scale={[0.88,1.14,0.42]}><sphereGeometry args={[irisSize,20,18]}/><primitive object={materials.iris} attach="material"/></mesh>
   <mesh position={[0,-HEAD_R*0.052,HEAD_R*1.067]} scale={[0.88,0.62,0.3]}><sphereGeometry args={[irisSize*0.72,16,14]}/><primitive object={materials.irisLight} attach="material"/></mesh>
   <mesh position={[0,HEAD_R*0.005,HEAD_R*1.078]} scale={[0.72,1.18,0.36]}><sphereGeometry args={[pupilSize,16,14]}/><primitive object={materials.pupil} attach="material"/></mesh>
   <mesh position={[-side*HEAD_R*0.026,HEAD_R*0.064,HEAD_R*1.09]}><sphereGeometry args={[HEAD_R*0.034*FACE,12,12]}/><primitive object={materials.hl} attach="material"/></mesh>
   <mesh position={[side*HEAD_R*0.045,-HEAD_R*0.045,HEAD_R*1.092]}><sphereGeometry args={[HEAD_R*0.014*FACE,10,10]}/><primitive object={materials.hl} attach="material"/></mesh>
  </group>
  <mesh position={[side*HEAD_R*0.30,HEAD_R*0.12,HEAD_R*1.025]} rotation={[0,0,side*0.04]} scale={[1.08,0.72,0.55]}><torusGeometry args={[eyeSize*0.84,HEAD_R*0.026,8,24,Math.PI]}/><primitive object={materials.eye} attach="material"/></mesh>
  <mesh ref={side<0?lidL:lidR} name={side<0?"EyelidL":"EyelidR"} position={[side*HEAD_R*0.30,HEAD_R*0.17,HEAD_R*1.04]} scale={[1.02,0.045,0.62]}><sphereGeometry args={[lidSize,18,14]}/><primitive object={materials.lid} attach="material"/></mesh>
 </group>))}
 <mesh ref={browL} name="BrowL" position={[-HEAD_R*0.30,browBaseY,HEAD_R*0.88]}><capsuleGeometry args={[browH,browW*0.55,5,8]}/><primitive object={materials.brow} attach="material"/></mesh><mesh ref={browR} name="BrowR" position={[HEAD_R*0.30,browBaseY,HEAD_R*0.88]}><capsuleGeometry args={[browH,browW*0.55,5,8]}/><primitive object={materials.brow} attach="material"/></mesh>
 <group name="Mouth" position={[0,-HEAD_R*0.28,HEAD_R*0.92]}><mesh ref={m=>{mouthRefs.current.smile=m;}} rotation={[0,0,Math.PI]} scale={0.0001} visible={false}><torusGeometry args={[HEAD_R*0.145*FACE,HEAD_R*0.014*FACE,8,24,Math.PI]}/><primitive object={materials.mouth} attach="material"/></mesh><mesh ref={m=>{mouthRefs.current.bigSmile=m;}} scale={0.0001} visible={false}><circleGeometry args={[HEAD_R*0.135*FACE,24]}/><primitive object={materials.mouth} attach="material"/></mesh><mesh ref={m=>{mouthRefs.current.frown=m;}} scale={0.0001} visible={false}><torusGeometry args={[HEAD_R*0.14*FACE,HEAD_R*0.022*FACE,8,20,Math.PI]}/><primitive object={materials.mouth} attach="material"/></mesh><mesh ref={m=>{mouthRefs.current.openO=m;}} scale={0.0001} visible={false}><torusGeometry args={[HEAD_R*0.085*FACE,HEAD_R*0.042*FACE,10,20]}/><primitive object={materials.mouth} attach="material"/></mesh><mesh ref={m=>{mouthRefs.current.flat=m;}} scale={0.0001} visible={false}><boxGeometry args={[HEAD_R*0.16*FACE,HEAD_R*0.016*FACE,HEAD_R*0.018]}/><primitive object={materials.mouth} attach="material"/></mesh><mesh ref={m=>{mouthRefs.current.wobble=m;}} rotation={[0,0,0.3]} scale={0.0001} visible={false}><torusGeometry args={[HEAD_R*0.13*FACE,HEAD_R*0.022*FACE,8,20,Math.PI*0.7]}/><primitive object={materials.mouth} attach="material"/></mesh></group>
 <group ref={tipGroup} name="Tip" position={[0,HEAD_R*0.92,0]}><mesh position={[0,STEM_LEN*0.5,0]}><cylinderGeometry args={[TIP_R*0.22,TIP_R*0.28,STEM_LEN,8]}/><primitive object={materials.skin} attach="material"/></mesh><mesh ref={tip} position={[0,STEM_LEN+TIP_R*0.85,0]}><sphereGeometry args={[TIP_R,14,14]}/><primitive object={materials.tipMat} attach="material"/><mesh ref={glow}><sphereGeometry args={[TIP_R*2.1,12,12]}/><primitive object={materials.glowMat} attach="material"/></mesh></mesh></group></group></group>;
});